name    'hairmare-hairmareyumrepo'
version '0.2.0-dev'
source 'http://github.com/hairmare/puppet-hairmareyumrepo'
author 'Lucas S. Bickel'
license 'Affero Gnu Public License, Version 3.0'
summary 'Setup the yum.hairmare.ch package repo'
description 'Setup the yum.hairmare.ch package repo'
project_page 'http://github.com/hairmare/puppet-hairmareyumrepo'
